### ISSUE TITLE
Method System.Diagnostics.Contracts.Contract.Requres<T> has missing Conditional attribute

### ISSUE THREAD

**Issue by kant2002** [Microsoft/CodeContracts#12]
Method `System.Diagnostics.Contracts.Contract.Requres<T>` should be decorated with `[Conditional("CONTRACTS_FULL")]`.
Right now when using Code Contracts and turn off runtime checking, in place where `Contract.Requires<T>` used, produced exception like that:

> An assembly (probably "TestAssembly") must be rewritten using the code contracts binary rewriter (CCRewrite) because it is calling Contract.Requires<TException> and the CONTRACTS_FULL symbol is defined.  Remove any explicit definitions of the CONTRACTS_FULL symbol from your project and rebuild.  CCRewrite can be downloaded from http://go.microsoft.com/fwlink/?LinkID=169180.   After the rewriter is installed, it can be enabled in Visual Studio from the project's Properties page on the Code Contracts pane.  Ensure that "Perform Runtime Contract Checking" is enabled, which will define CONTRACTS_FULL.

**Comment by sharwell** [comment]
This method is not annotated *by design*. Many methods of the `Contract` class, such as `Requires` (the non-generic form) are only enabled when specifically requested. In many ways, they are similar to `Debug.Assert`, provided for the purpose of explicitly stating conditions and verifying them during debug builds, but disabled during final releases (with no runtime checking overhead in the final release).

`Requires<T>`, on the other hand, is an expression of behavior that should *always* occur in the application. For example, this contract can be used on public API surfaces in libraries where external callers may not be using Code Contracts and expect particular exceptions to be thrown in response to invalid inputs. Code using this method must always use the rewriter, yet still has the option of defining or removing the `CONTRACTS_FULL` preprocessor directive to control the runtime behavior of all other contracts.

**Comment by kant2002** [comment]
Thanks for explanation. I have a project where I was trying to enforce the Code Contracts. Having Code Contracts enabled during development was significantly slow me down during development and I decide to adopt them gradually and have different configuration.

I use VS tools for Code Contracts and want to turn them off on the dev solution configuration. I was not able do that. Maybe I miss some other option in the VS tooling how I could configure such scenario.

I post this on Connect but not receive any feedback. Maybe I miss something in the docs. I will try to play again with more understanding. Still this is not very obvious message.

**Comment by aarondandy** [comment]
@kant2002 
This is how I setup my configurations: http://mediocresoft.com/things/code-contracts-from-new-project-to-nuget#build-config

**Comment by mike-barnett** [comment]
@aarondandy: Thanks so much for writing such a fantastic guide! It is great to see people in the community doing such great work!

**Comment by kant2002** [comment]
@aarondandy Thank you so much. A lot of helpful stuff in your guide!

**Comment by aarondandy** [comment]
:+1:
