### ISSUE TITLE
CodeContracts and SCA (CA1062)

### ISSUE THREAD

**Issue by njannink** [microsoft/CodeContracts#174]
This issue is out there for many years now and I really would like it to be solved.

When I use:

Contracts.Requires<ArgumentException>(arg 1= null, nameof(arg));

Then Static Code Analysis still complains with CA1062:

CA1062 : Microsoft.Design : In externally visible method 'XXXXX', validate parameter 'arg' before using it.

**Comment by tom-englert** [comment]
"Static Code Analysis" and "CodeContracts" are two distinct tools, looking at the code in different ways.

To have this solved, "Static Code Analysis" would need to learn that ```Contract.Requires(arg != null)```is merely the same as ```if (arg != null) throw...```, but this would be a "Static Code Analysis" issue. I see no way how this could be done by "CodeContracts".

However if you use "CodeContracts" to care about null checks, I see no benefit from running a second tool doing the same thing again. I always use a predefined rule set that turns of CA1062.

**Comment by jbcutting** [comment]
I agree this should be fixed. It would be great if the FxCop team would make supporting changes. However, there's an optimization that has been discussed that could also solve this problem. See #90.

**Comment by petergummer** [comment]
How sad.

**Comment by njannink** [comment]
Last commit in this repo is from 2017 and who uses CodeContracts anno 2020. Cleaning up my issues list

**Comment by mwwhited** [comment]
How saw... they were so nice and should be much easier now with Roslyn.  But I guess no one at Microsoft wanted to rewrite the stuff from before.

**Comment by SergeyTeplyakov** [comment]
@mwwhited Me and my collegue tried to rewrite CC with Roslyn a few years ago and we've found that the set of challenges just changed but not disappeared. The source generators feature that is going to be a key feature of C# 9 won't help too much because the generators can't change the code, so it means that the "source rewriter" needs to do all the heavy lifting manually. And some features, like contract inheritance or even postconditions are quite hard to implement on the source level as well.
