### ISSUE TITLE
ccrewrite adds invalid source reference to PDB file

### ISSUE THREAD

**Issue by tom-englert** [Microsoft/CodeContracts#45]
The source for the project is at https://tomstoolbox.codeplex.com/SourceControl/latest (Feature/Default branch, Desktop module)

When "Perform Runtime Contract Checking (Preconditions)" is on, an invalid source file reference is added to the .pdb file. 

The class is TomsToolbox.Desktop.DependencyObjectExtensions.DependencyPropertyEventWrapper`1, which implements TomsToolbox.Core.INotifyChanged.

Without the rewriter the pdb contains a link to the correct source file, but when enabling the rewriter the pdb contains an additional link to the source file of TomsToolbox.Core.INotifyChanged, which is in a different project!

Now the NuGet package manager can't find this 
source file, since it's from another project, and the NuGet symbol package is considered invalid.

![cc-pdb](https://cloud.githubusercontent.com/assets/10229954/7666754/b07083b0-fbf0-11e4-9ac8-d10112586163.png)

**Comment by hubuk** [comment]
This is by design. Additional source code file comes from a contract for INotifyChanged interface (NotifyChangedContract class) which is being injected into Desktop assembly by ccrewrite.
This allows you for example to step into the contract defined for an interface method from the implementing type during debugging.
You can specify symbol package source files manually or submit a feature request to nuget project to make nuget read pdb files for list of source files needed.

**Comment by tom-englert** [comment]
Not a bug here, the problem is on NuGet side.
