### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#92]
@sharwell I started getting following build error:

![image](https://cloud.githubusercontent.com/assets/726448/8564857/d8eab5c6-2504-11e5-96a1-7cdb12aa5a31.png)

:question:  Am I doing something wrong?

**Comment by SergeyTeplyakov** [comment]
Close as not reproduces any more.

**Comment by sharwell** [comment]
This is a weird case due to the build configuration for various solution configurations and platforms. I believe you chose a pair where the Adornments project was not selected for build, but one or more of the projects which use it was. When the dependent project tried to build, it couldn't find the dependency.

**Comment by SergeyTeplyakov** [comment]
Ok. Sounds good.
